/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface CatalogCrudMasterDTO
 */
export interface CatalogCrudMasterDTO {
    /**
     *
     * @type {string}
     * @memberof CatalogCrudMasterDTO
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof CatalogCrudMasterDTO
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof CatalogCrudMasterDTO
     */
    subsetType?: CatalogCrudMasterDTOTypeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum CatalogCrudMasterDTOTypeEnum {
    ITEM_SERVICE = 'ITEM_SERVICE',
    CURRENCY = 'CURRENCY',
    UNITS = 'UNITS',
    PRICE_LABEL = 'PRICE_LABEL',
    CALCULATION_ON = 'CALCULATION_ON',
}

