/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CatalogCrudMasterDTO } from "./catalog-crud-master-dto";

/**
 *
 * @export
 * @interface CatalogCrudMaster
 */
export interface CatalogCrudMaster {
    /**
     *
     * @type {string}
     * @memberof CatalogCrudMaster
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof CatalogCrudMaster
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof CatalogCrudMaster
     */
    type?: CatalogCrudMasterTypeEnum;

catalogCrudMasterDTOList?: Array<CatalogCrudMasterDTO>
}

/**
 * @export
 * @enum {string}
 */
export enum CatalogCrudMasterTypeEnum {
    ITEM_SERVICE = 'ITEM_SERVICE',
    CURRENCY = 'CURRENCY',
    UNITS = 'UNITS',
    PRICE_LABEL = 'PRICE_LABEL',
    CALCULATION_ON = 'CALCULATION_ON',
}

